/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include "stm32f407xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



void delay(void)
{
	for(uint32_t i=0; i<500000; i++);
}
int main(void)
{
	GPIO_Handle GPIOLed;//Creation of structure variable
	GPIOLed.pGPIOx=GPIOD;
	GPIOLed.GPIO_PinConf.GPIO_PinNumber= GPIO_PIN_NO_12;
	GPIOLed.GPIO_PinConf.GPIO_PinMode=GPIO_MODE_OUT;
	GPIOLed.GPIO_PinConf.GPIO_PinSpeed=GPIO_OP_TYPE_HS;
	GPIOLed.GPIO_PinConf.GPIO_PinOpType=GPIO_OP_TYPE_OD;//1. GPIO_OP_TYPE_PP, 2. GPIO_OP_TYPE_OD
	GPIOLed.GPIO_PinConf.GPIO_PinPuPdControl=GPIO_PIN_PU;//1. GPIO_NO_PUPD, 2.GPIO_PIN_PU  

	GPIO_PeriClckInit(GPIOD,ENABLE);
	GPIO_init(&GPIOLed);
	while(1)
	{
		GPIO_ToggleOutputPin(GPIOD,GPIO_PIN_NO_12);
		delay();
	}

}
